farmAssist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
]

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path("", views.home, name="home"),
    path("connect/", views.connect, name="connect"),
    path("login/", views.login_request, name="login"),
    path("register/", views.register_request, name="register"),
    path("logout", views.logout_request, name= "logout"),
    path("create_event", views.create_event, name="create_event"),
    path("change_crops", views.change_crops, name="change_crops"),
    path("add_comment", views.add_comment, name="add_comment"),
]

pages/templates/connect.html
{% load static %}
<!DOCTYPE html>\
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/connect-style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon2.ico">
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <title>FarmAssist</title>
<style>
  .comment-section ul li{
    color: black;
    background-color: white;
    border-style: groove;
  }
</style>
</head>
<body>
  <header>
    <nav class="navbar">
        <a href="{% url 'pages:home' %}" class="nav-branding">FarmAssist</a>
        <ul class="nav-menu">
            <li class="nav-item">
                <a href="{% url 'pages:home' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'pages:connect' %}" class="nav-link">Connect</a>
            </li>
            {% if user.is_authenticated %} 

             <li class="nav-item">
                <a href="{% url 'pages:logout' %}" class="nav-link">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>

            {% else %} 

            <li class="nav-item">
                <a href="{% url 'pages:login' %}" class="nav-link">Login</a>
            </li>

            {% endif %} 
        </ul>
        <div class="hamburger">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>
</header>
<script src="{% static 'script.js' %}"></script>
<div class="popup-btn-conatiner">
    <a href="#form-container" class="popup-btn">Add New Event</a>
    </div>
<div class="form-container" id="form-container">
<div class="contact-box">
  <div class="left"></div>
  <div class="right">
  
  <h2>Create An Event</h2> <a href="#" class="popup-close">&times;</a>
   <form action="{% url 'pages:create_event' %}" method="POST">
    {% csrf_token %}
     <input type="hidden" class="field"  name="_captcha" value="false">
      <input type="text" class="field" name="title" placeholder="Title" required>
      <input type="text" class="field"  name="location" placeholder="Location" required>
      <input type="text" class="field"  name="time" placeholder="hh:mm" required>
      <input type="text" class="field"  name="date" placeholder="YYYY-MM-DD" required>
       <input type="text" class ="textarea" placeholder="Event Details..." name="description" required>
      <button type="submit" class="btn">Create</button>
   </form>
   </div>
</div>
</div>

<section class="portfolio defaultMargin" id="portfolio">
  <div class="title__container">
    <h2>Meetups and Events</h2>
    <p>Check out nearby meetups and events.</p>
  </div>

  <div class="container">
  {% for i in meetup %}
    <div class="design">
      <div class="background"></div>
      <div class="portfolio__container">
       <a href="#popup_{{ i.title }}">
       <span class="link"></span>
       </a>
        <h3>{{ i.title }}</h3>
        <p>Location: {{ i.location }} </p>
        <p>Time: {{ i.starttime }} {{ i.date }} </p>
        <p>{{ i.description }}</p>
        </div>
      </div>
      <div class="popup1" id="popup_{{ i.title }}">
        <div class="popup-dialog">
           <section class="popup-content">
            <div class="popup-header">
                <p> {{ i.title }} </p>
                <a href="#" class="popup-close">&times;</a>
            </div>
        
              <div class="popup-body">
                <div class="popup-image-event"></div>
                <div class="popup-text">
                <p><b>Contact: </b>{{ i.creatorid.email }}</p>
                <p><b>Location: </b>{{ i.location }}</p>
                <p><b>About: </b>{{ i.description }}</p><br>
                <p><b>Comments: </b></p>
                <div class="comment-section">
                  {% for k in comment %}
                  {% if k.post.postid == i.postid %}
                  <ul>
                    <li><b>{{ k.username.username }}</b><br>
                    {{ k.content }} </li>
                  </ul>
                  {% endif %}
                  {% endfor %}
                </div>
                <form action="{% url 'pages:add_comment' %}" method="POST">
                  {% csrf_token %}
                   <input type="hidden" class="field"  name="_captcha" value="false">
                   <input type="hidden" class="field" name="post" value={{ i.postid }}>
                     <input type="text" class ="textarea" placeholder="Add a Comment..." name="comment" required>
                    <button type="submit" class="comment-btn">Comment</button>
                 </form>
            </div>
              </div>
               
           </section>
        </div>
    </div>
    {% endfor %}
  </div>
  </section>

<section class="portfolio defaultMargin" id="portfolio">
      <div class="title__container">
        <h2>Connect with other farmers</h2>
        <p>Check out what others have been planting.</p>
      </div>
      <div class="container">
      {% for i in users %}
        {% if not i.is_superuser %} 
        <div class="design">
          <div class="background"></div>
          <div class="portfolio__container">
           <a href="#popup_{{ i.username }}">
           <span class="link"></span>
           </a>
            <h3>{{ i.username }}</h3>
            <p>{{ i.email }}</p>
            <div class="image">
              <img src="{% static 'img/profile.jpg' %}" alt="" />
            </div>
          </div>
        </div>
        <div class="popup1" id="popup_{{ i.username }}">
        <div class="popup-dialog">
           <section class="popup-content">
            <div class="popup-header">
                <p>Connect with {{ i.username }} </p>
                <a href="#" class="popup-close">&times;</a>
            </div>
        
              <div class="popup-body">
                <div class="popup-image"></div>
                <div class="popup-text">
                <p><b>Name: </b> {{ i.first_name }}</p>
                <p> <b>Email: </b>{{ i.email }}</p><br>
                <p><b>About: </b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis saepe veritatis, velit ea ex sint, libero officiis repudiandae autem, praesentium consequatur atque, enim blanditiis aut consequuntur ad. Necessitatibus, iste, magnam.</p><br>
            </div>
              </div>
               
           </section>
        </div>
    </div>
    {% endif %} 
    {% endfor %}
  </div>
  </section>
</body>
</html>

pages/templates/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Title</title>
  </head>
 <body>

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

pages/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/home-style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon2.ico">
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <title>FarmAssist</title>
    <style>
        .table {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
          margin-top: 30px;
          margin-bottom: 30px;
        }
        
        .table td, .table th {
          border: 1px solid #ddd;
          padding: 8px;
          text-align: center;
        }
        
        .table tr:nth-child(even){background-color: #f2f2f2;}
        
        .table tr:hover {background-color: #ddd;}
        
        .table th {
          padding-top: 12px;
          padding-bottom: 12px;
          max-width: 50px;
          text-align: center;
          background-color: #04AA6D;
          color: white;
        }
        #selector {
    margin-top: 10%;
    margin-left: 5%;
    margin-right: 5%;
}


h2{
    padding-bottom: 10px;
    margin-bottom: 10px;
    margin-left: 10px;
}

.field{
    width: 30%;
    max-width: 200px;
    padding: 0.5rem 1rem;
    border: 2px solid rgba(0, 0, 0, 0);
    background-color: rgba(230, 230, 230, 0.6);
    margin-bottom: 22px;
    transition: .3s;
}

select {
    font-size: 1.5rem;
    padding 1em 5em 1em 1.5em;
    background: #04AA6D;
    color: white;
    border: 0;
}

.custom-select{
    position: relative;
    margin-bottom: 10px;
    margin-top: 10px;
   
}

.field:hover {
    background-color: rgba(0, 0, 0, 0.1);
}

.field:focus{
    background-color: #fff;
    border: 2px solid rgba(30, 85, 250, 0.47);
}

.area{
    min-height: 150px;
}

.btn{
    width: 50%;
    max-width: 300px;
    padding: 0.5rem 1rem;
    font-size: 1.1rem;
    background-color: #C0C0C0;
    outline: none;
    border: none;
    color: #fff;
    transition: 0.3s;
    margin-top: 10px;
    margin-bottom: 10px;
}

.btn:hover{
    background-color: gray;
}


.popup-btn-conatiner {
    width: 100%;
    height: 100%;
    vertical-align: middle;
    display: block;
    height: auto;
    margin-top: 30px;
    margin-left: 20px;
    margin-bottom: 20px;
   
}

.popup-btn {
    text-decoration: none;
    padding: 1rem;
    background: black;
    border-radius: 5px;
    color: white;

}

.popup-btn{
  transition: 0.3s ease-out;
}

.popup-btn:hover {
    color: #C0C0C0;
}

.addEvent {
    display:none;
    background: rgba(0, 0, 0, .8);
    position: fixed;
    left: 0;
    top: 0;
    height: 100%;
    width: 100%;
    z-index: 2;
 
}

.form-container:target {
    display: flex;
}


.form-container {

    display: none;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 100%;
    padding: 50px 100px;
}

.form-container:after {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
}

.contact-box{
    max-width: 850px;
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    justify-content: center;
    align-items: center;
    text-align: center;
    background-color: #fff;
    box-shadow: 0px 0px 19px 5px rgba(0, 0, 0, 0.19);
}



h2{
    padding-bottom: 10px;
    margin-bottom: 10px;
}
#main-text{
    font-size: 30px;
    text-align: center;
}

h2:after{
    content: '';
    position: absolute;
    left: 50%;
    bottom: 0;
    transform: translateX(-50%);
    height: 4px;
    width: 50px;
    border-radius: 2px;
}


.field{
    width: 100%;
    padding: 0.5rem 1rem;
    border: 2px solid rgba(0, 0, 0, 0);
    background-color: rgba(230, 230, 230, 0.6);
    margin-bottom: 22px;
    transition: .3s;
}

.field:hover {
    background-color: rgba(0, 0, 0, 0.1);
}

.field:focus{
    background-color: #fff;
    border: 2px solid rgba(30, 85, 250, 0.47);
}

.area{
    min-height: 150px;
}

.btn{
    width: 100%;
    padding: 0.5rem 1rem;
    font-size: 1.1rem;
    background-color: #C0C0C0;
    outline: none;
    border: none;
    color: #fff;
    transition: 0.3s;
}

.btn:hover{
    background-color: gray;
}

@media screen and (max-width:880px){
    .contact-box{
        grid-template-columns: 1fr;
    }
   
    .left{
        height: 200px;
    }
}

.popup-close {
    color: black;
    text-decoration: none;
    position: absolute;
    top: 1rem;
    right: 1rem;
    font-size: 40px;
    margin-bottom: 30px;
    margin-top: 50px;
}
        </style>
</head>
<body>
<header>
    <nav class="navbar">
        <a href="{% url 'pages:home' %}" class="nav-branding">FarmAssist</a>
        <ul class="nav-menu">
            <li class="nav-item">
                <a href="{% url 'pages:home' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'pages:connect' %}" class="nav-link">Connect</a>
            </li>
            {% if user.is_authenticated %} 

             <li class="nav-item">
                <a href="{% url 'pages:logout' %}" class="nav-link">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>

            {% else %} 

            <li class="nav-item">
                <a href="{% url 'pages:login' %}" class="nav-link">Login</a>
            </li>

            {% endif %} 
        </ul>
        <div class="hamburger">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>
</header>
<div class="popup-btn-conatiner">
    <a href="#form-container" class="popup-btn">Edit Produce Selection</a>
    </div>
<div class="form-container" id="form-container">

<div class="contact-box">
    <h2>Change your produce selection</h2> <a href="#" class="popup-close">&times;</a>

    <div id="selector">

   <form action="{% url 'pages:change_crops' %}" method="POST">
    {% csrf_token %}
     <h4>Change slot 1:</h4>
<div class="custom-select" >
  <select name="slot1" placehorder="{{ slot1.type }}">
    <option value=0>Select produce:</option>
    <option value="Broccoli">Broccoli</option>
    <option value="Carrots">Carrots</option>
    <option value="Kale">Kale</option>
    <option value="Potatoes">Potatoes</option>
    <option value="Soy Beans">Soy Beans</option>
  </select>
</div>
      <h4>Change slot 2:</h4>
      <div class="custom-select">
  <select name="slot2">
    <option value=0>Select produce:</option>
    <option value="Broccoli">Broccoli</option>
    <option value="Carrots">Carrots</option>
    <option value="Kale">Kale</option>
    <option value="Potatoes">Potatoes</option>
    <option value="Soy Beans">Soy Beans</option>
  </select>
</div>
       <h4>Change slot 3:</h4>
      <div class="custom-select">
  <select name="slot3">
    <option value=0>Select produce:</option>
    <option value="Broccoli">Broccoli</option>
    <option value="Carrots">Carrots</option>
    <option value="Kale">Kale</option>
    <option value="Potatoes">Potatoes</option>
    <option value="Soy Beans">Soy Beans</option>
  </select>
</div>
      <h4>Change slot 4:</h4>
      <div class="custom-select">
  <select name="slot4">
    <option value=0>Select produce:</option>
    <option value="Broccoli">Broccoli</option>
    <option value="Carrots">Carrots</option>
    <option value="Kale">Kale</option>
    <option value="Potatoes">Potatoes</option>
    <option value="Soy Beans">Soy Beans</option>
  </select>
</div>
      <button type="submit" class="btn">Update</button>
   </form>
       
   
</div>
   
</div>
</div>
<script src="{% static 'script.js' %}"></script>
<div class="container">
    <div class="row mt-4">
        <div class="col">
            <!--Table-->
            <h2 id="main-text">Your Crops</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Location</th>
                        <th scope="col">Crop</th>
                        <th scope="col">Plant Date</th>
                        <th scope="col">Estimated Harvest Date</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in crop %}
                    <tr>
                        <th scope="row">{{ i.location }}</th>
                        <td>{{ i.type.name }}</td>
                        <td>{{ i.plantdate }}</td>
                        <td>{{ i.harvestdate }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--END TABLE-->
            <h2>Water Tank</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Reading</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in tank %}
                    <tr>
                        <th scope="row">{{ i.time }}</th>
                        <td>{{ i.reading }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <h2>Moisture Readings</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Location</th>
                        <th scope="col">Reading</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in moisture %}
                    <tr>
                        <th scope="row">{{ i.time }}</th>
                        <td>{{ i.location }}</td>
                        <td>{{ i.reading }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--END TABLE-->
            <h2>Temperature Readings</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Reading</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in temperature %}
                    <tr>
                        <th scope="row">{{ i.time }}</th>
                        <td>{{ i.reading }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--END TABLE-->

            <h2>Lighting Readings</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Location</th>
                        <th scope="col">Reading</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in lighting %}
                    <tr>
                        <th scope="row">{{ i.time }}</th>
                        <td>{{ i.location }}</td>
                        <td>{{ i.reading }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--END TABLE-->

            <h2>Humidity Readings</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Reading</th>

                    </tr>
                </thead>
                <tbody>
                    {% for i in humidity %}
                    <tr>
                        <th scope="row">{{ i.time }}</th>
                        <td>{{ i.reading }}</td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--END TABLE-->
        </div>
    </div>
</div>
</body>
</html>

pages/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login @FarmAssist</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
  </head>
  <body>
    <div class="container">
      <div class="wrapper">
        <div class="title"><span>Login to FarmAssist</span></div>
        <form method="POST" action="">
          {% csrf_token %}
          <div class="row">
            <i class="fas fa-user"></i>
            <input type="text" name="username" placeholder="Username..." class="form-control" required>
          </div>
          <div class="row">
            <i class="fas fa-lock"></i>
            <input type="password" name="password" placeholder="Password..." class="form-control" required>
          </div>
          <div class="row button">
            <input class="btn login_btn" type="submit" value="Login">
          </div>
        
        </form>
        {% for message in messages %}
          <p id=""messages">{{message}}</p>
        {% endfor %}
        
        <div class="d-flex justify-content-center links"></div>
          <p class="text-center">Don't have an account? <a href="{% url 'pages:register' %}">Create an account</a>.</p>
        </div>
        </div>
    </div>

  </body>
</html>

pages/templates/register.html
{% extends "header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         
<title>Register</title>
<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	

	{% for message in messages %}
		<p id=""messages">{{message}}</p>
  	{% endfor %}
	<div class="mt-4">
		<p class="text-center">If you already have an account, <a href="{% url 'pages:login' %}">login</a> instead.</p>
	</div>
</div>

{% endblock %}